# Generated by Django 5.0.1 on 2024-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_cheptel_owner_alter_intervention_hive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='owner',
            field=models.CharField(default='CedricJ', max_length=40),
        ),
    ]
