# Generated by Django 5.0.1 on 2024-01-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_intervention_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='type_action',
            field=models.CharField(choices=[('Suppression_cellules_royales', 'Suppression_cellules_royales'), ('verification_santé', 'Vérification santé'), ('Récolte', 'Récolte'), ('Pose_hausses', 'Pose hausses'), ('Destruction', 'Destruction'), ('Traitement', 'Traitement')], max_length=100),
        ),
    ]
